### ISSUE TITLE
non riesco a usare scrape (git bash in Win10): Exec format error

### ISSUE THREAD

**Issue by ffxx68** [aborruso/scrape-cli#7]

**Comment by ffxx68** [comment]
```
$ wget "https://github.com/aborruso/scrape-cli/releases/download/v1.0/scrape"
...
$ sudo chmod +x scrape
$ ./scrape     
 bash: ./scrape: cannot execute binary file: Exec format error
```

**Comment by aborruso** [comment]
Ciao @ffxx68 io l'ho appena testato in questo modo

```
wget "https://github.com/aborruso/scrape-cli/releases/download/v1.0/scrape"
chmod +x ./scrape
```

E poi un test su Repubblica con 

```
curl "https://www.repubblica.it/" | ./scrape -be '.entry__media+ .entry__content a'
```

**Comment by aborruso** [comment]
@ffxx68 su che sistema operativo sei? Che versione?

**Comment by ffxx68** [comment]
sto provando con la bash git su Win10, immagino ci sia un problema qui

Il giorno ven 20 nov 2020 alle ore 17:14 Andrea Borruso <
notifications@github.com> ha scritto:

**Comment by aborruso** [comment]
@ffxx68 bash git su Win10 non credo sia un vero Linux e quell'eseguibile è compilato per Linux.

Quindi o lo usi in un ambiente Linux, o provi a usare l'eseguibile per win https://github.com/aborruso/scrape-cli/releases/download/v1.0/scrape.exe

Purtroppo non ho esperienza con la bash git su Win10

**Comment by ffxx68** [comment]
Vero: gitbash non è Linux !! è che non ho una macchina Linux al momento ma volevo comunque provare, ma l'eseguibile che mi hai passato va. OK per ora, grazie!

**Comment by aborruso** [comment]
@ffxx68 come hai scoperto scrape?

Cosa vorresti provare a fare? Se serve una mano, torna, che (se sono in grado) mi fa piacere

**Comment by ffxx68** [comment]
sto provando lo script per l'estrazione dei dati da iss_epicentro...
